package com.acl.pojo;

import java.io.Serializable;


public class SysFile implements Serializable {
    
	private static final long serialVersionUID = -2985368214942340167L;
    private Integer id;
    private String fileName;
    private String fileType;
    private Long fileSize;
    private String filePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.id
     *
     * @return the value of t_sys_file.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.id
     *
     * @param id the value for t_sys_file.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.file_name
     *
     * @return the value of t_sys_file.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.file_name
     *
     * @param fileName the value for t_sys_file.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.file_type
     *
     * @return the value of t_sys_file.file_type
     *
     * @mbggenerated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.file_type
     *
     * @param fileType the value for t_sys_file.file_type
     *
     * @mbggenerated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.file_size
     *
     * @return the value of t_sys_file.file_size
     *
     * @mbggenerated
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.file_size
     *
     * @param fileSize the value for t_sys_file.file_size
     *
     * @mbggenerated
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_file.file_path
     *
     * @return the value of t_sys_file.file_path
     *
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_file.file_path
     *
     * @param filePath the value for t_sys_file.file_path
     *
     * @mbggenerated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
}